<h1>Basic Python</h1>

<h2>1. Split this string</h2>

In [1]:
s = "Hi there am Jaisnavi here"
s.split()

['Hi', 'there', 'am', 'Jaisnavi', 'here']

<h2>2. Use .format() to print the following string.</h2>

<h2>Output should be: The diameter of Earth is 12742 kilometers.</h2>

In [4]:
planet = "Earth"
diameter = 12742

In [9]:
print('The diameter of {} is {} kilometers'.format(planet,diameter))

The diameter of Earth is 12742 kilometers


<h2>3. In this nest dictionary grab the word 'hello'</h2>

In [12]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

<h2>Numpy</h2>

In [13]:
import numpy as np

<h2>4.1 Create an array of 10 zeros?</h2>

<h2>4.2 Create an array of 10 fives?</h2>

In [14]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
b = np.ones(10)*5
b

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

<h2>5. Create an array of all the even integers from 20 to 35</h2>

In [16]:
S = np.arange(20,35,2)
S

array([20, 22, 24, 26, 28, 30, 32, 34])

<h2>6. Create a 3x3 matrix with values ranging from 0 to 8</h2>

In [17]:
b = np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h2>7. Concatenate a and b
    
    
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])</h2>

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

<h1>Pandas</h1>


<h2>8. Create a dataframe with 3 rows and 2 columns</h2>

In [19]:
import pandas as pd
d = {"names":["Geetha","Jayashree","Kiruthika"],"age":[21,21,21]}
df = pd.DataFrame(d)
df

names  age
0     Geetha   21
1  Jayashree   21
2  Kiruthika   21

<h2>9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023</h2>

In [20]:
P = pd.date_range(start='1-1-2023',end='10-2-2023')
for val in P:
  print(val);

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00
2023-02-11 00:00:00
2023-02-12 00:00:00
2023-02-13 00:00:00
2023-02-14 00:00:00
2023-02-15 00:00:00
2023-02-16 00:00:00
2023-02-17 00:00:00
2023-02-18 00:00:00
2023-02-19 00:00:00


<h2>10. Create 2D list to DataFrame</h2>

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24